export const districts =[
  {
    img:"https://www.keralatourism.org/images/destination/mobile/aquatourism_in_alappuzha20131031102829_292_1.jpg",
    name:"ALLAPUZHA",
    title:""
  },
  {
    img:"https://assets-news.housing.com/news/wp-content/uploads/2022/09/07010326/Pathanamthitta-FEATURE-compressed.jpg",
    name:"PATHANAMTHITTA",
  },
  {
    img:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/de/f0/eb/backwater-tourism.jpg?w=700&h=-1&s=1",
    name:"KOCHI",
  },
  {
    img:"https://www.holidify.com/images/cmsuploads/compressed/at_20190109034758_20190109034951.jpg",
    name:"THRISSUR",
  },
  {
    img:"https://keralatourism.travel/images/destinations/places-to-visit/idukki/munnar-idukki-kerala-tourism-entry-fee-timings-holidays-reviews-small.jpg",
    name:"IDUKKI",
  },
  {
    img:"https://assets-news.housing.com/news/wp-content/uploads/2022/08/14104744/Top-tourist-attractions-in-Malappuram-and-things-to-do.jpg",
    name:"MALAPURAM",
  },
  {
    img:"https://yometro.com/images/places/sargaalya-kerela-art.jpg",
    name:"KOZHIKODE",
  },
  {
    img:"https://assets-news.housing.com/news/wp-content/uploads/2022/06/29070406/Places-to-visit-in-Wayanad-feature-compressed.jpg",
    name:"WAYANNAD",
  },
  {
    img:"https://www.trawell.in/admin/images/upload/129720103Trivandrum_Main.jpg",
    name:"THIRUVANANTHAPURAM",
  },
  {
    img:"https://www.dtpckannur.com/public/img/slider/banner-04-res.jpg",
    name:"KANNUR",
  },
  {
    img:"https://www.tourmyindia.com/blog//wp-content/uploads/2021/11/Best-Places-to-Visit-in-Palakkad-Kerala.jpg",
    name:"PALAKAD",
  },
  {
    img:"https://tripvibe.online/wp-content/uploads/2021/06/Vagamon-1.jpg",
    name:"KOTTAYAM",
  },
  {
    img:"https://img.traveltriangle.com/blog/wp-content/uploads/2018/04/Jatayu%E2%80%99s-Earth-Centre-kollam-kb6592.jpg",
    name:"KOLLAM",
  },
  {
    img:"https://www.keralatourism.org/images/destination/mobile/aquatourism_in_kasaragod20131107114603_306_1.jpg",
    name:"KASARGOD",
  },

]
